### ISSUE TITLE
Release 6.11

### ISSUE THREAD

**Issue by musm** [JuliaIO/HDF5.jl#1005]
@mkitti  I'm planning on making a new release based on the current commit. I don't think anything between now and 6.10 was backward incompatible or breaking, but wanted to double check before initiating the release.

**Comment by mkitti** [comment]
I believe this would be a good time to release as well since we have made a lot of changes that *should*be non-breaking.

There is more `HDF5Context` related changes I would like to incorporate eventually, but they are not necessary for a release. The further application of that might be breaking. I will try to divide that into non-breaking and breaking components.

**Comment by mkitti** [comment]
Surely you mean 0.16.11, right?
