### ISSUE TITLE
Read complex numbers from HDF5

### ISSUE THREAD

**Issue by garrison** [JuliaIO/HDF5.jl#180]
Although there is no standardized way of storing complex numbers in an HDF5 file, a few de facto standards have emerged using compound datatypes.  Octave, for instance, uses a compound datatype with fields "real" and "imag", while pytables and h5py both use fields "r" and "i".

Since [the goal is to get to the point where we can read any HDF5 file](https://github.com/timholy/HDF5.jl/issues/92#issuecomment-42146612), I think it would be wonderful if HDF5.jl could load arrays from these files into arrays of complex numbers.

The following Python program can be used to make an HDF5 file with two matrices: one real and one complex:

```
#!/usr/bin/env python

import h5py

f = h5py.File("complex.h5", "w")
f["m1"] = [2, 1]
f["m2"] = [2, 1j]
f.close()
```

The goal is to get Julia to load both matrices using the following code:

```
using HDF5

println(h5read("complex.h5", "m1"))
println(h5read("complex.h5", "m2"))
```

However, currently it fails on the last line while reading the array `m2` containing complex numbers.

**Comment by bhawkins** [comment]
Sorry to necro an old issue, but I was struggling with this today and this issue was high on the list of search results. The `reinterpret` trick suggested here and elsewhere no longer seems to work. Using PyCall to use h5py directly works, of course, but I'd prefer to avoid that route.

I'm a pretty green Julia programmer, but I managed to cobble something together in this gist:

https://gist.github.com/bhawkins/6edaab42b9907758eeb58a24399b9426

You can use the low-level HDF5.jl routines to create the h5py complex type given a Julia Complex{T} and vice-versa.

The other difficulty I had was not being able to slice datasets with compound types, so you can't write `dset[:,1] = z`.  Fortunately `hyperslab` (not exported) seems to work fine in this scenario, and you can use it in conjunction with the low-level `h5d_read` and `h5d_write` to read/write slices. I'd love to know if there's a higher-level way to do this.

I also noticed that `h5t_get_member_name` only works with a pointer, whereas the other H5T methods are happy with `HDF5Datatype` objects.

**Comment by kleinhenz** [comment]
I think that complex number support would be nice to have built into HDF5.jl. Requiring a general serialization framework like JLD or writing custom code just to conveniently save/load arrays of complex numbers feels like overkill. The precedent of h5py/octave seem to indicate that transparently adding complex number support to hdf5 wrappers via compound datatypes is a reasonable approach. Would people be open to a pull request implementing this approach?

**Comment by musm** [comment]
@kleinhenz  PRs that improve HDF5.jl are always welcome

**Comment by tknopp** [comment]
@kleinhenz, @musm: I have started working on this, on this branch:
  https://github.com/JuliaIO/HDF5.jl/tree/tk/complex

write support is there, although I am not sure if I added it to the correct layer. Maybe it would be better to let `ScalarOrString` include the complex type.

Read support is still missing.

**Comment by tknopp** [comment]
Or more precisely: I know how to read and interpret the data, but we somehow need to special case the compound data code in that case, and I am not sure what would be the cleanest way for that.
