### ISSUE TITLE
FileIO integration

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/HDF5.jl#278]
I see that the file format is registered in FileIO in https://github.com/JuliaIO/FileIO.jl/blob/master/src/registry.jl#L106 
But it seems like there is no load function defined for it in `HDF5` itself (JuliaGL/GLVisualize.jl#44).
Is there a reason for that? 

Best,
Simon

**Comment by timholy** [comment]
No reason other than it hasn't been added.

I think the JLD one is also importing `load` and `save`, and with the redesign it shouldn't be.

**Comment by SimonDanisch** [comment]
Good to know! Well then, I might create a PR if If I find the time.

**Comment by ggggggggg** [comment]
What should these do? `load` seems straightforward, just return an HDF5File. `save` is less, say it is passed an array, what should it call the dataset that it writes to? What happens if you call `save` again, write to a new dataset? Is `save(fname,data)` supposed to be able to be followed by `load(fname)==data` being true?

**Comment by jonas-schulze** [comment]
Are there any updates on this?

I was trying out [DrWatson.jl](https://juliadynamics.github.io/DrWatson.jl/dev/) and saving any `.hdf5` file fails with
```
Error encountered while saving "/Users/jonas/Research/FooProject/data/sim/prefix_N=50.hdf5".
Fatal error:
ERROR: LoadError: UndefVarError: save not defined
```

**Comment by musm** [comment]
Doesn't this work? (I haven't tried it) Looking at https://github.com/JuliaIO/FileIO.jl/blob/master/src/registry.jl#L303 it seems like it's in the registry?
