### ISSUE TITLE
Implement "bitshuffle" filter for data compression

### ISSUE THREAD

**Issue by eschnett** [JuliaIO/HDF5.jl#285]
This paper http://arxiv.org/pdf/1503.00638v3.pdf describes a "bitshuffle" filter for HDF5 files for floating-point data. According to the paper, it leads to a higher compression ratio than HDF5's "shuffle" filter.

We should implement this (maybe asking the authors for their source code, which is apparently already SSE and AVX optimized), and if it looks good, tug the HDF5 team's sleeves to incorporate this into the HDF5 library.

**Comment by simonster** [comment]
Note that the algorithm is only "nearly lossless" and apparently slower to read than blosc. Unless you have massive amounts of data, I'm not sure it's worth it.

**Comment by eschnett** [comment]
The overall algorithm described in the paper is lossy, but the bitshuffle part (instead of shuffling bytes) is lossless. The timings in table 2 show that (in their case, whatever that means in general) writing was faster than with Blosc.

**Comment by david-macmahon** [comment]
This issue is a bit dated now, but for the record, we've used the bitshuffle filter from here with HDF5.jl v0.15.7 successfully: https://github.com/kiyo-masui/bitshuffle.git

HDF5.jl v0.15.7 adds a "filter" keyword to `create_dataset` that makes this possible:

```julia
ds, dt = create_dataset(h5, "data", data, chunk=(256,1,256), filter=(32008, 0, 0, 2))
```

32008 is the bitshuffle filter id, the first 0 is the H5Z_FLAG_MANDATORY flag, and the remaining integers are the options for the bitshuffle plugin: 0 for default block size, and 2 (BSHUF_H5_COMPRESS_LZ4) for simultaneous in-cache LZ4 compression.

We have to build/install it outside of Julia.  Sometimes we run into system HDF5 vs HDF5_jll HDF versionitis, especially on older systems where system HDF5 is 1.8 yet uses the same `/usr/local/hdf5/lib/plugin` as its plugin directory, but it does work when everything is setup properly.  Including it as part of HDF5_jll would avoid these problems.

We did encounter a problem with its default "OMP enabled" build.  It resulted in lots of CPU utilization and very poor performance.  We never dug into why that happened.  Instead we just configured the `setup.cfg` file to disable OMP (following the `setup.cfg.example` file's example) and that works great for us.

**Comment by david-macmahon** [comment]
It seems that the blosc compression library already implements a bitshuffle option with 0 being no shuffle, 1 being byte shuffle, and 2 being bit shuffle.  Unfortunately, `H5ZBlosc.jl` treats the `shuffle` option as a `Bool` rather than a `Cint` so the bit shuffle option is not exposed.

**Comment by david-macmahon** [comment]
It turns out `Blosc.jl` also treats shuffling as a boolean choice thereby preventing the use of `c-blosc`'s bit shuffle capabilities.  I've created a [PR for that] (https://github.com/JuliaIO/Blosc.jl/pull/88).  If/when that gets pulled it will be pretty straightforward to create a PR for `H5ZBlosc.jl`

**Comment by musm** [comment]
Yeah after that PR is merged we can update H5ZBlosc for the additional capability

**Comment by musm** [comment]
@david-macmahon   https://github.com/JuliaIO/HDF5.jl/blob/master/filters/H5Zblosc/src/H5Zblosc.jl#L133 

Where were you finding that H5Zblosc is restricting the shuffle argument to booleans?

**Comment by musm** [comment]
Note, I've tagged a new release of Blosc with permits the bitshuffle option to be passed in. As far as I see, it works seamlessly with the latest HDF5 release.

**Comment by david-macmahon** [comment]
I just PR #899 for this.  The restriction was more on the usage side.  The commit log message spells out the details of why the BITSHUFLLE option was not accessible previously.
