### ISSUE TITLE
Error: Reading Attribute String

### ISSUE THREAD

**Issue by r-chris** [JuliaIO/HDF5.jl#332]
When loading a string (not unicode) attribute from a HDF5 file, the following error is thrown:

`ERROR: MethodError: no method matching unsafe_string(::Array{UInt8,1})`

Full error context:

``` julia
julia> h5readattr("bar.h5", "foo")

HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139787026885632:
  #000: ../../../src/H5A.c line 642 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 641 in H5A_read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
  #002: ../../../src/H5T.c line 4548 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
ERROR: MethodError: no method matching unsafe_string(::Array{UInt8,1})
Closest candidates are:
  unsafe_string(::Cstring) at c.jl:187
  unsafe_string(::Union{Ptr{Int8},Ptr{UInt8}}) at strings/basic.jl:56
  unsafe_string(::Union{Ptr{Int8},Ptr{UInt8}}, ::Integer) at strings/basic.jl:52
 in h5a_get_name(::Int32) at ~/.julia/v0.5/HDF5/src/plain.jl:2153
 in h5a_read(::Int32, ::Int32, ::Array{Ptr{UInt8},1}) at ~/.julia/v0.5/HDF5/src/plain.jl:2111
 in read(::HDF5.HDF5Attribute, ::Type{String}) at ~/.julia/v0.5/HDF5/src/plain.jl:1294
 in read(::HDF5.HDF5Attribute) at ~/.julia/v0.5/HDF5/src/plain.jl:1213
 in collect(::Base.Generator{Array{String,1},HDF5.##3#4}) at ./array.jl:307
 in h5readattr(::String, ::String) at ~/.julia/v0.5/HDF5/src/plain.jl:673
```

**Comment by r-chris** [comment]
`h5dump bar.h5`

```bash
HDF5 "bar.h5" {
GROUP "/" {
   DATASET "foo" {
      DATATYPE  H5T_STD_I64LE
      DATASPACE  SIMPLE { ( 10 ) / ( 10 ) }
      DATA {
      (0): 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
      }
      ATTRIBUTE "c" {
         DATATYPE  H5T_STRING {
            STRSIZE 30;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
         DATASPACE  SCALAR
         DATA {
         (0): "value for metadata parameter c"
         }
      }
   }
}
}
```

**Comment by r-chris** [comment]
Btw. it works fine when loading the same hdf5 file with unicode attribute (e.g. `ATTRIBUTE/DATATYPE/CSET` would be: `CSET H5T_CSET_UTF8;`)

**Comment by r-chris** [comment]
Follow-up: it looks like `h5py` has a similar problem, but it doesn't like to read `unicode` attributes (and writes `string` by default). This makes HDF5 files (with string attributes) created by `h5py` currently difficult to use in julia.

**Comment by stevengj** [comment]
If HDF5.jl is calling `unsafe_string` on an array, that is a bug.  It should just call `String`.

**Comment by stevengj** [comment]
I just looked at the source code, and `h5a_get_name(::Int32) at ~/.julia/v0.5/HDF5/src/plain.jl:2153` is calling `@compat String(...)`, not `unsafe_string`.   Maybe you are using an out-of-date version of HDF5.jl?

**Comment by r-chris** [comment]
I'll certainly try the latest master version - thanks for looking into this!

**Comment by r-chris** [comment]
Hi Steven, I'm sorry to say, but the call to `unsafe_string` is still present in the latest release as well as the current master. When you looked at the code, I believe you saw the call in `h5f_get_name` not actually in `h5a_get_name`, which has now moved to line 2147 (it's line 2153 in release 0.6.6): https://github.com/JuliaIO/HDF5.jl/blob/master/src/plain.jl#L2147

**Comment by stevengj** [comment]
@r-chris, that seems like a bug; can you file a PR to change it to a `String` call?

All of the other calls to `unsafe_string` look correct (the other calls are on pointers).

**Comment by r-chris** [comment]
Yeah, already in the works, just didn't get to press "Create Pull Request", yet

**Comment by andyferris** [comment]
I filed a PR at #337

**Comment by andyferris** [comment]
OK my PR resolves one issue with the incorrect use of `unsafe_string`.

There seems to be an ongoing Julia v0.5 issue with reading ASCII attributes. The error I get is:

```
julia> h5readattr("foo.h5", "A")
HDF5-DIAG: Error detected in HDF5 (1.8.16) thread 139770510441472:
  #000: ../../../src/H5A.c line 642 in H5Aread(): unable to read attribute
    major: Attribute
    minor: Read failed
  #001: ../../../src/H5Aint.c line 641 in H5A_read(): unable to convert between src and dst datatypes
    major: Attribute
    minor: Feature is unsupported
  #002: ../../../src/H5T.c line 4548 in H5T_path_find(): no appropriate function for conversion path
    major: Datatype
    minor: Unable to initialize object
ERROR: Error reading attribute c
 in h5a_read(::Int32, ::Int32, ::Array{Ptr{UInt8},1}) at /home/ferris/.julia/v0.5/HDF5/src/plain.jl:2105
 in read(::HDF5.HDF5Attribute, ::Type{String}) at /home/ferris/.julia/v0.5/HDF5/src/plain.jl:1292
 in read(::HDF5.HDF5Attribute) at /home/ferris/.julia/v0.5/HDF5/src/plain.jl:1211
 in collect(::Base.Generator{Array{String,1},HDF5.##3#4}) at ./array.jl:307
 in h5readattr(::String, ::String) at /home/ferris/.julia/v0.5/HDF5/src/plain.jl:671

julia> h5readattr("bar.h5", "A")
Dict{String,String} with 2 entries:
  "c" => "value for metadata parameter c"
  "d" => "metadata d"
```
where `foo.h5` uses ASCII encoding and `bar.h5` uses UTF-8. Both work on Julia 0.4 with HDF5.jl master.

I'm not very familiar with the codebase of HDF5.jl but I can see that some strange things are happening in v0.5 because `Compat.UTF8String === Compat.ASCIIString === String`. One result is that `ASCII_LINK_PROPERTIES` and `ASCII_ATTRIBUTE_PROPERTIES` is initialized with `cset(String)` which is the UTF-8 one, and this struck me as odd. However I think all of this only affects creating attributes in `h5a_create()` (so it's impossible to write one in ASCII encoding in Julia 0.5).

I'm still searching fo

**Comment by andyferris** [comment]
OK more digging found the real problem. It is in `read(::DataSetOrAttrribute, ::Type{S<:String})`, on the line that gets the `cset` from the type of the thing we are filling, rather than the source.
```
function read{S<:String}(obj::DatasetOrAttribute, ::Type{S})
    local ret::S
    objtype = datatype(obj)
    try
        if h5t_is_variable_str(objtype.id)
            buf = Ptr{UInt8}[C_NULL]
            memtype_id = h5t_copy(H5T_C_S1)
            h5t_set_size(memtype_id, H5T_VARIABLE)
            if isleaftype(S)
                h5t_set_cset(memtype_id, 0)
            else
                h5t_set_cset(memtype_id, h5t_get_cset(datatype(obj)))
            end
            readarray(obj, memtype_id, buf)
            ret = @compat unsafe_string(buf[1])
        else
            n = h5t_get_size(objtype.id)
            pad = h5t_get_strpad(objtype.id)
            buf = Array(UInt8, n)
            readarray(obj, objtype.id, buf)
			pbuf = @compat String(buf)
            ret = unpad(pbuf, pad)
        end
    finally
        close(objtype)
    end
    ret
end
```

**Comment by andyferris** [comment]
I think this `if` statement can be removed for Julia v0.5. The only thing that will get there will be `String` and the only allowed encodings are UTF8 and ASCII which happen to both be bit-compatible with `String`. We should determine the encoding from the HDF5 source not the Julia type.

**Comment by andyferris** [comment]
Further digging shows that the entire HDF5 type system for strings relies on the fact that ASCII encoded strings and UTF-8 encoded strings are represented by distinct Julia types. Form example, `hdf5_to_julia(obj)` will return `String` for both encodings on Julia v0.5, and later on the encoding is determined from the Julia datatype rather than the HDF5 attribute...

I feel I'm getting out of my depth here so I'm going to ping @timholy and @simonster as the most prolific contributers to this package in order to highlight this potential design issue. Possibly this is trivial to fix and the problem is only in the method I copy-pasted above, but you guys might remember if this assumption crops up elsewhere. However, I think a great amount of simplification could be gained if you dropped v0.4 support.

If I didn't have to support Julia 0.4 I think I could fix this without asking for feedback. Is it safe to replace [this part](https://github.com/JuliaIO/HDF5.jl/blob/master/src/plain.jl#L1287#L1291) of `read{S<:String}(obj::DatasetOrAttribute, ::Type{S})`
```julia
if isleaftype(S)
    h5t_set_cset(memtype_id, cset(S))
else
    h5t_set_cset(memtype_id, h5t_get_cset(datatype(obj)))
end
```
with
```julia
h5t_set_cset(memtype_id, h5t_get_cset(datatype(obj)))
```
on Julia 0.4 also?
