### ISSUE TITLE
Installing HDF5 asks for sudo password

### ISSUE THREAD

**Issue by dawbarton** [JuliaIO/HDF5.jl#519]
I installed HDF5.jl (rather I installed MAT.jl and got HDF5 as a dependency) and was rather surprised that I was suddenly asked for my sudo password with no apparent reason. After further inspection I figured out that it was trying to install the hdf5 package via my distro package manager. This sort of automatic install is great, but it's probably worth printing a message saying what it is trying to do with sudo as I don't just type my passwords into terminals when randomly prompted...

**Comment by vvjn** [comment]
Agreed. Also, on Ubuntu at least, if you type in the sudo password it doesn't actually install hdf5-tools (I think that's the package name) anyway. It just fails and I end up installing hdf5-tools on the terminal and rebuilding HDF5.jl. So most likely the best thing to do is to fail the build with a message saying what to do instead of trying to install hdf5-tools automatically.

**Comment by musm** [comment]
should be fixed by the latest version when it goes through #555
