### ISSUE TITLE
Matlab datetime / H5Aopen(): unable to load attribute info from object header for attribute: 'MATLAB_class'

### ISSUE THREAD

**Issue by StefanPofahl** [JuliaIO/HDF5.jl#626]
Hi,

it seems that HDF5.jl has an issue importing variables of the Matlab class "datetime".
This class is currently also missing in Octave:
https://savannah.gnu.org/bugs/?47032
I mention this here because Andrew Janke writes here, that there is free access to his 
class definition of "datetime": [...]/inst/datetime.m

Attached the error messages.

Regards,

Stefan

[HDF5-DIAG_ Error detected in HDF5 (1.10.5) thread 0_.txt](https://github.com/JuliaIO/HDF5.jl/files/4615315/HDF5-DIAG_.Error.detected.in.HDF5.1.10.5.thread.0_.txt)

**Comment by musm** [comment]
I'm not sure what's actionable here? We need more details. Are you importing and HDF5 saved from matlab or a `.mat` file.

**Comment by musm** [comment]
I just saw https://github.com/JuliaIO/MAT.jl/issues/133, I don't think this is a HDF5.jl specific issue, which looks like was helped by https://github.com/JuliaIO/MAT.jl/pull/129. If there is a still a problem, best to post in `Mat.jl` repo since it sounds like this is dealing with `.mat` files, unless there is something specific to the hdf5 format we are failing to deal with.
