### ISSUE TITLE
File organization and renaming?

### ISSUE THREAD

**Issue by musm** [JuliaIO/HDF5.jl#653]
Changes I'd like to see, for example reorg into submodules the following:

- Library (H5)
- Attribute (H5A)
- Dataset (H5D)
- Dimension Scale (H5DS)
- Error (H5E)
- File (H5F)
- Group (H5G)
- Identifier (H5I)
- Link (H5L)
- MATLAB (H5ML)
- Object (H5O)
- Property (H5P)
- Reference (H5R)
- HDF5 references
- Dataspace (H5S)
- Datatype (H5T)
- Filters and Compression (H5Z)

So that `H5Fget_access_plist` becomes `H5F.get_name` instead of `h5f_get_name`. I guess this could be done without a breaking change because these are internal implementation details in the package. 

I also think the exported names from this package are not very readable/julian:

- `g_create`  should just be `create_group` this would also help with things like tab-completion etc.  Or perhaps even better
`H5G.create` so that  `a_create`  would be   `H5A.create` 

These could be a deprecated in a  breaking release.

- Also more fully supporting the AbstractDict interface and replacing `DataFile` supertype with the `AbstractDict` one makes a lot of sense to me.

I'm not sure if such changes would warrant a new package, e.g.,  H5JL where we can implement such breaking changes without having to worry about deprecation policies.  I'm just throwing this out there as a wild idea.  
Perhaps this is not worth it and it would be better to incrementally improve this package as we are doing (I'm also not against this) 

Curious about what others think about this. 

Furthermore:
```
    HDF5Attribute, HDF5File, HDF5Group, HDF5Dataset, HDF5Datatype,
    HDF5Dataspace, HDF5Object, HDF5Properties, HDF5Vlen, HDF5ChunkStorage,
```
should not have the HDF5 prefix.

cc @kleinhenz @jmert

**Comment by kleinhenz** [comment]
I think the first change is probably actually quite breaking since although these low level functions are technically not exported one of the main uses of the library is low-level access to hdf5 library routines so I suspect the bare wrapper functions are used quite a bit in user code. I think if we did this we would need to have a good deprecation strategy.

I definitely agree that the higher level routines could be reworked to be more readable, and moving to an AbstractDict type of interface seems like a good idea. It seems like some renaming of functions could be done relatively easily with deprecations.

One thing that I would like to do would be to create a serialization/deserialization interface that provides an extensible mechanisms for saving/loading custom types in a user defined format. I think this is a somewhat separate niche from JLD/JLD2 because sometimes it is important to have manual control over the serialization for exchange with other programs. I'm not sure if this would be a better fit for a new package or if it should go in here.

**Comment by musm** [comment]
> I think the first change is probably actually quite breaking since although these low level functions are technically not exported one of the main uses of the library is low-level access to hdf5 library routines so I suspect the bare wrapper functions are used quite a bit in user code. I think if we did this we would need to have a good deprecation strategy.

True, OTOH the functions should be relatively easy to deprecate with Julia's internal deprecation machinery. 

I am just trying to gauge if it's a net positive change or not.

**Comment by kleinhenz** [comment]
Are there any other libraries that use submodules as a main part of their interface? I haven't seen this pattern much in julia at least in comparison to how things are done in python.

**Comment by musm** [comment]
Perhaps this is more generally agreeable:
```
    HDF5Attribute, HDF5File, HDF5Group, HDF5Dataset, HDF5Datatype,
    HDF5Dataspace, HDF5Object, HDF5Properties, HDF5Vlen, HDF5ChunkStorage,
```
should not have the `HDF5` prefix.

**Comment by musm** [comment]
@jmert  any thoughts on things you would like to see ?

**Comment by jmert** [comment]
I guess my thoughts (in no particular order) are:

- If the `HDF5` prefixes are removed from the custom types, then I would hesitate to export them since `File`, `Group`, `Attribute`, etc are all pretty generic names. It's not a bad compromise since `HDF5.File` is only one character longer than `HDF5File`.

- I would advocate for keeping all the C API (`h5f_open`, `h5d_create`, etc) and corresponding types at the top-level scope of the package and unexported like they already are (modulo naming fixes like in e.g. #678). This would allow viewing this package as kind of serving two roles — providing the raw wrappers necessary to just talk to the HDF5 library itself, and a second view that adds higher-level Julian constructs. My take is that it's the higher-level wrappers that should be under consideration for burying into sub-modules.

- I don't have strong opinions on whether some of the high-level wrapper functionality is shuttled down into sub-modules, but if they are, then the modules themselves should definitely be exported so that after a `using HDF5` something like `H5G.create` is immediately usable.

- As for the abstract dict interface, I'd support using `keys()` instead of `names()` and the like since e.g. writing datasets/attributes uses normal dict-like `setindex!` syntax. I'm not as immediately sure about having `HDF5File <: AbstractDict` rather than just duck-typing generically, but I could definitely be convinced that it's the correct path. (I just haven't thought about this aspect at all yet.)

**Comment by musm** [comment]
> If the HDF5 prefixes are removed from the custom types, then I would hesitate to export them since File, Group, Attribute, etc are all pretty generic names. It's not a bad compromise since HDF5.File is only one character longer than HDF5File.

Yes the idea is to make them public functions that are *not* exported.


>  providing the raw wrappers necessary to just talk to the HDF5 library itself, and a second view that adds higher-level Julian constructs. My take is that it's the higher-level wrappers that should be under consideration for burying into sub-modules.

We are on the same page here.

> I don't have strong opinions on whether some of the high-level wrapper functionality is shuttled down into sub-modules, but if they are, then the modules themselves should definitely be exported so that after a using HDF5 something like H5G.create is immediately usable.

Yeah I'm not 100% sure either, but if we did they would need to be exported. I'm trying to find some examples of other Julia packages that do this, I think there are some but I can't of the top my head think of their names.

**Comment by musm** [comment]
I'm teetering on whether it really makes sense here to define submodules with all the various sub `HDF5` modules  a la `H5F`, `H50`, etc.    My original motivation was inspired from the h5py and MATLAB hdf5 interfaces to the libraries, who do this.  In some sense, it adds more complexity and a bigger maintenance burden to do so, all in the name of, what, compartmentalization? That doesn't seem really worth it to me.

**Comment by musm** [comment]
Notes:
Consider `gettype` -> `get_type`
Figure out what to do with `name` and `filename`  (exported)

**Comment by musm** [comment]
Notes:
`objinfo`
`info` 

(consolidate)

**Comment by musm** [comment]
Closing since I think we are converging to  the underscore convention.
